const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('motivate')
    .setDescription('Get a dose of motivation to power through your day!'),

  async execute(interaction) {
    const quotes = [
      "✨ *Believe you can and you're halfway there.* – Theodore Roosevelt",
      "🌟 *Push yourself, because no one else is going to do it for you.*",
      "💡 *Don’t watch the clock; do what it does. Keep going.* – Sam Levenson",
      "🔥 *Great things never come from comfort zones.*",
      "🧠 *Your limitation—it's only your imagination.*",
      "🏆 *Dream it. Wish it. Do it.*",
      "✨ *The only way to do great work is to love what you do.* – Steve Jobs",
      "🌟 *Success is not final, failure is not fatal: It is the courage to continue that counts.* – Winston Churchill",
      "💡 *Your time is limited, don't waste it living someone else's life.* – Steve Jobs",
      "🔥 *Believe you can and you're halfway there.* – Theodore Roosevelt",
      "🧠 *I can't change the direction of the wind, but I can adjust my sails to always reach my destination.* – Jimmy Dean",
      "🏆 *Nothing is impossible, the word itself says 'I'm possible'!* – Audrey Hepburn",
      "💥 *Do what you can, with what you have, where you are.* – Theodore Roosevelt",
      "🚀 *If you look at what you have in life, you'll always have more.* – Oprah Winfrey",
      "🔑 *Life is 10% what happens to me and 90% how I react to it.* – Charles Swindoll",
      "🎯 *The best revenge is massive success.* – Frank Sinatra",
      "🌈 *Whether you think you can or you think you can't, you're right.* – Henry Ford",
      "⚡ *You miss 100% of the shots you don't take.* – Wayne Gretzky",
      "🌊 *The mind is everything. What you think you become.* – Buddha",
      "🌍 *The two most important days in your life are the day you are born and the day you find out why.* – Mark Twain",
      "🌱 *An unexamined life is not worth living.* – Socrates",
      "🌻 *Eighty percent of success is showing up.* – Woody Allen",
      "🌎 *Don't judge each day by the harvest you reap but by the seeds that you plant.* – Robert Louis Stevenson",
      "🌞 *The future belongs to those who believe in the beauty of their dreams.* – Eleanor Roosevelt",
      "🌴 *A person who never made a mistake never tried anything new.* – Albert Einstein",
      "🌺 *A journey of a thousand miles begins with a single step.* – Lao Tzu",
      "🌄 *What lies behind us and what lies before us are tiny matters compared to what lies within us.* – Ralph Waldo Emerson",
      "🌅 *The only person you are destined to become is the person you decide to be.* – Ralph Waldo Emerson",
      "🌠 *Go confidently in the direction of your dreams. Live the life you have imagined.* – Henry David Thoreau",
      "🌌 *When I let go of what I am, I become what I might be.* – Lao Tzu",
      "🌉 *First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.* – Aristotle",
      "🌋 *If the wind will not serve, take to the oars.* – Latin Proverb",
      "🌏 *You can't fall if you don't climb. But there's no joy in living your whole life on the ground.* – Unknown",
      "🌑 *We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.* – Marie Curie",
      "🌓 *Too many of us are not living our dreams because we are living our fears.* – Les Brown",
      "🌔 *Challenges are what make life interesting and overcoming them is what makes life meaningful.* – Joshua J. Marine",
      "🌕 *If you want to lift yourself up, lift up someone else.* – Booker T. Washington",
      "🌖 *I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.* – Maya Angelou",
      "🌗 *Either you run the day, or the day runs you.* – Jim Rohn",
      "🌘 *Whether you think you can or you think you can't, you're right.* – Henry Ford",
      "🌙 *Build your own dreams, or someone else will hire you to build theirs.* – Farrah Gray",
      "☀️ *The question isn't who is going to let me; it's who is going to stop me.* – Ayn Rand",
      "⭐ *If you hear a voice within you say "you cannot paint," then by all means paint and that voice will be silenced.* – Vincent Van Gogh",
      "🌟 *There is only one way to avoid criticism: do nothing, say nothing, and be nothing.* – Aristotle",
      "💫 *The only limit to our realization of tomorrow will be our doubts of today.* – Franklin D. Roosevelt",
      "✨ *What you get by achieving your goals is not as important as what you become by achieving your goals.* – Zig Ziglar",
      "🌪️ *You become what you believe.* – Oprah Winfrey",
      "🌀 *The most difficult thing is the decision to act, the rest is merely tenacity.* – Amelia Earhart",
      "🌁 *It's during our darkest moments that we must focus to see the light.* – Aristotle Onassis",
      "🌃 *Start where you are. Use what you have. Do what you can.* – Arthur Ashe",
      "🌄 *Fall seven times and stand up eight.* – Japanese Proverb",
      "🌅 *Everything you've ever wanted is on the other side of fear.* – George Addair",
      "🌆 *We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.* – Plato",
      "🌇 *Nothing will work unless you do.* – Maya Angelou",
      "🌉 *The only place where success comes before work is in the dictionary.* – Vidal Sassoon",
      "🌊 *I find that the harder I work, the more luck I seem to have.* – Thomas Jefferson",
      "🌋 *Don't be afraid to give up the good to go for the great.* – John D. Rockefeller",
      "🌌 *Some people dream of success, while other people get up every morning and make it happen.* – Wayne Huizenga",
      "🌍 *The secret of getting ahead is getting started.* – Mark Twain",
      "🌎 *The best time to plant a tree was 20 years ago. The second best time is now.* – Chinese Proverb",
      "🌏 *It's hard to beat a person who never gives up.* – Babe Ruth",
      "🌑 *I am not a product of my circumstances. I am a product of my decisions.* – Stephen Covey",
      "🌒 *The most common way people give up their power is by thinking they don't have any.* – Alice Walker",
      "🌓 *The most difficult decision is the decision to act, the rest is merely tenacity.* – Amelia Earhart",
      "🌔 *Every strike brings me closer to the next home run.* – Babe Ruth",
      "🌕 *Definiteness of purpose is the starting point of all achievement.* – W. Clement Stone",
      "🌖 *Life isn't about getting and having, it's about giving and being.* – Kevin Kruse",
      "🌗 *Life is what happens to you while you're busy making other plans.* – John Lennon",
      "🌘 *We become what we think about.* – Earl Nightingale",
      "🌙 *Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.* – Mark Twain",
      "☀️ *The only limit to our realization of tomorrow is our doubts of today.* – Franklin D. Roosevelt",
      "⭐ *What you do today can improve all your tomorrows.* – Ralph Marston",
      "🌟 *You may be disappointed if you fail, but you are doomed if you don't try.* – Beverly Sills",
      "💫 *The only way to discover the limits of the possible is to go beyond them into the impossible.* – Arthur C. Clarke",
      "✨ *You don't have to be great to start, but you have to start to be great.* – Zig Ziglar",
      "🌪️ *The only person you are destined to become is the person you decide to be.* – Ralph Waldo Emerson",
      "🌀 *The best revenge is massive success.* – Frank Sinatra",
      "🌁 *Certain things catch your eye, but pursue only those that capture the heart.* – Ancient Indian Proverb",
      "🌃 *Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.* – Norman Vincent Peale",
      "🌄 *If you can dream it, you can achieve it.* – Zig Ziglar",
      "🌅 *Success is walking from failure to failure with no loss of enthusiasm.* – Winston Churchill",
      "🌆 *Try not to become a person of success, but rather try to become a person of value.* – Albert Einstein",
      "🌇 *At his best, man is the noblest of all animals; separated from law and justice he is the worst.* – Aristotle",
      "🌉 *Where there is love there is life.* – Mahatma Gandhi",
      "🌊 *First they ignore you, then they laugh at you, then they fight you, then you win.* – Mahatma Gandhi",
      "🌋 *Talent wins games, but teamwork and intelligence win championships.* – Michael Jordan",
      "🌌 *A man is but the product of his thoughts. What he thinks, he becomes.* – Mahatma Gandhi",
      "🌍 *The weak can never forgive. Forgiveness is the attribute of the strong.* – Mahatma Gandhi",
      "🌎 *Live as if you were to die tomorrow. Learn as if you were to live forever.* – Mahatma Gandhi",
      "🌏 *Strength does not come from physical capacity. It comes from an indomitable will.* – Mahatma Gandhi",
      "🌑 *Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.* – Thomas A. Edison",
      "🌒 *We may encounter many defeats but we must not be defeated.* – Maya Angelou",
      "🌓 *Knowing is not enough; we must apply. Wishing is not enough; we must do.* – Johann Wolfgang von Goethe",
      "🌔 *Imagine your life is perfect in every respect; what would it look like?* – Brian Tracy",
      "🌕 *We generate fears while we sit. We overcome them by action.* – Dr. Henry Link",
      "🌖 *Whether you think you can or think you can't, you're right.* – Henry Ford",
      "🌗 *Security is mostly a superstition. Life is either a daring adventure or nothing.* – Helen Keller",
      "🌘 *The man who has confidence in himself gains the confidence of others.* – Hasidic Proverb",
      "🌙 *The only limit to our realization of tomorrow is our doubts of today.* – Franklin D. Roosevelt",
      "☀️ *Creativity is intelligence having fun.* – Albert Einstein",
      "⭐ *Do what you can, with what you have, where you are.* – Theodore Roosevelt",
      "🌟 *You are never too old to set another goal or to dream a new dream.* – C.S. Lewis"
      "💥 *Success doesn’t just find you. You have to go out and get it.*",
      "🚀 *The harder you work for something, the greater you’ll feel when you achieve it.*",
      "🔑 *Failure is not the opposite of success, it's part of success.*",
      "🎯 *Stay focused and never give up. The beginning is always the hardest.*"
    ];

    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];

    const embed = new EmbedBuilder()
      .setColor('#00FFAB')
      .setTitle('💬 Your Daily Motivation')
      .setDescription(randomQuote)
      .setFooter({ text: 'Let’s get it, champ! 💪' });

    await interaction.reply({ embeds: [embed] });
  }
};
