const { SlashCommandBuilder } = require('discord.js');

const truths = [
  "What’s your biggest fear?",
  "Have you ever cheated in an exam?",
  "Who was your first crush?",
  "What’s a secret you’ve never told anyone?",
  "What is something illegal you’ve done?",
  "Have you ever lied to your parents?",
  "What’s the most embarrassing thing you’ve done?",
  "What’s something you've done that you still feel guilty about?",
  "Have you ever lied to get out of trouble?",
  "What’s your weirdest dream ever?",
  "What’s the most embarrassing thing in your search history?",
  "Who was your first crush and do they know?",
  "Have you ever stalked someone online?",
  "What’s the biggest lie you’ve ever told?",
  "Do you still sleep with a stuffed toy or blanket?",
  "Have you ever cheated on anything important?",
  "What’s one thing you’ve never told your parents?",
  "Who do you secretly envy and why?",
  "Have you ever faked being sick for attention?",
  "What’s your most awkward romantic moment?",
  "Do you have a secret talent no one knows about?",
  "What’s the cringiest message you’ve ever sent?",
  "What’s one thing you’ve done that you’d never admit publicly?",
  "Have you ever been jealous of your best friend?",
  "What’s the meanest thing you’ve said to someone?",
  "What’s one thing you regret saying in a chat or DM?",
  "Who was your first kiss and how was it?",
  "What’s your biggest insecurity?",
  "Do you talk behind people’s backs?",
  "Have you ever had a crush on someone in this server?",
  "What’s the most immature thing you still do?",
  "What’s a rumor you secretly liked hearing about yourself?",
  "Have you ever faked being friends with someone?",
  "What’s something super childish you secretly enjoy?",
  "What’s your guilty pleasure TV show or movie?",
  "What’s the weirdest thing you’ve done alone at home?",
  "Have you ever cried over a meme or video?",
  "What’s the dumbest thing you’ve argued about?",
  "Have you ever stolen something — even small?",
  "Who do you text the most and what do you talk about?",
  "Have you ever been caught lying?",
  "What’s a nickname you hated growing up?",
  "Do you have a crush on a fictional character?",
  "Have you ever ghosted someone?",
  "Do you still check your ex’s profile?",
  "Have you ever accidentally sent a message to the wrong person?",
  "What’s your most embarrassing memory from school?",
  "Have you ever made a fake account?",
  "What’s something you wish people didn’t know about you?",
  "Who is the most attractive person in this group?",
  "Have you ever pretended to like something just to fit in?",
  "What’s a secret you’ve kept from your best friend?",
  "What’s your most embarrassing habit?",
  "Have you ever tried to impress someone and failed badly?",
  "What’s your biggest turn-off?",
  "What’s something people always get wrong about you?",
  "Have you ever told a big lie and never admitted it?",
  "What’s a weird food combo you actually enjoy?",
  "What’s your deepest fear that no one knows?",
  "Who’s the last person you stalked online?",
  "Have you ever pretended to know something but didn’t?",
  "What’s your worst habit in relationships?",
  "Have you ever felt like you weren’t good enough?",
  "What’s the worst date you’ve ever been on?",
  "Have you ever been rejected badly?",
  "What’s one mistake you never want to repeat?",
  "What’s the weirdest message you've ever received?",
  "Have you ever secretly hated a gift?",
  "What’s your most cringe-worthy DM?",
  "Have you ever lied to a friend to avoid hanging out?",
  "What’s your most embarrassing selfie?",
  "What’s a goal you gave up on?",
  "What’s one thing you’re really bad at but pretend you’re not?",
  "Have you ever been caught singing or dancing alone?",
  "What’s the pettiest thing you’ve done during an argument?",
  "Have you ever laughed at something inappropriate?",
  "What’s your biggest social media regret?",
  "Do you keep any secrets from your family?",
  "Have you ever used someone just to get something?",
  "What’s your weirdest guilty pleasure?",
  "What’s your biggest regret in love?",
  "Have you ever liked someone way older or younger?",
  "Have you ever pretended to like a song or artist?",
  "What’s your weirdest obsession?",
  "Have you ever eavesdropped on someone intentionally?",
  "Have you ever had a crush on someone you shouldn’t?",
  "What’s the most dramatic thing you’ve ever done for attention?",
  "What’s one habit you can’t quit no matter what?",
  "What’s the worst gift you’ve ever received?",
  "Have you ever texted someone while angry and regretted it?",
  "What’s your strangest fantasy?",
  "Have you ever spread a secret you weren’t supposed to?",
  "What’s something you'd never admit in real life?",
  "Have you ever cheated on a game or test and got away with it?",
  "What’s a memory you wish you could delete?",
  "Have you ever faked a compliment?",
  "What’s your biggest fear about the future?",
  "Have you ever read someone else's messages?",
  "What’s the worst outfit you've ever worn?",
  "What’s something you secretly enjoy that others find weird?",
  "Have you ever caught feelings unexpectedly?",
  "What’s something you're proud of but never talk about?",
  "What’s your most unusual like or kink?",
  "Have you ever lied in a truth or dare game?",
  "Have you ever regretted saying 'I love you'?",
  "What’s something about your personality that you hide?",
  "Have you ever cried over someone who didn’t know you liked them?",
  "What’s the silliest thing you've cried about?",
  "Who’s someone you’d never want to see your search history?",
  "What’s a random secret you’ve been holding onto for years?",
  "What’s your guilty pleasure?",
  "What’s your weirdest habit?",
  "What’s a lie you told recently?",
  "Have you ever stalked someone on social media?",
  "What’s your biggest insecurity?",
  "What’s something you wish you could change about yourself?",
  "What’s the worst thing you’ve done to a friend?",
  "Have you ever had a crush on a teacher?",
  "What’s the weirdest dream you’ve had?",
  "What’s the most childish thing you still do?",
  "What’s your most embarrassing nickname?",
  "Have you ever broken something and blamed someone else?",
  "What’s a secret you kept from your best friend?",
  "Have you ever faked being sick to skip school?",
  "What’s the biggest mistake you’ve made?",
  "What’s your most irrational fear?",
  "Have you ever pretended to like a gift you hated?",
  "Have you ever lied to your crush?",
  "What’s your worst habit?",
  "Do you talk in your sleep?",
  "Have you ever been caught talking to yourself?",
  "What’s the dumbest thing you’ve ever done?",
  "Do you sing in the shower?",
  "What’s your most awkward moment?",
  "Have you ever sent a message to the wrong person?",
  "Have you ever peed your pants?",
  "What’s the silliest thing you’re afraid of?",
  "Do you have a fake social media account?",
  "What’s the longest you’ve gone without showering?",
  "What’s a food you pretend to like but actually hate?",
  "Have you ever Googled yourself?",
  "Do you still sleep with a stuffed toy?",
  "What’s your most embarrassing photo?",
  "Have you ever cried in public?",
  "What’s the last lie you told?",
  "Do you sing or dance when you're alone?",
  "What’s a rumor you helped spread?",
  "Have you ever been rejected?",
  "What’s your weirdest talent?",
  "Have you ever been caught sneaking out?",
  "Do you talk to your pets like they're humans?",
  "What’s the most cringe thing you’ve posted online?",
  "If you had to confess one secret right now, what would it be?"
];

const dares = [
  "Do 10 push-ups.",
  "Speak in a British accent for the next 5 minutes.",
  "Do your best chicken dance.",
  "Send a funny selfie to the group.",
  "Text your crush ‘I like you 😳’.",
  "Act like a monkey for 1 minute.",
  "Say the alphabet backwards.",
  "Eat a spoonful of something spicy.",
  "Record yourself doing 10 different accents.",
  "Try to juggle 3 random objects.",
  "Let someone write a status for your social media.",
  "Do your best evil villain laugh in voice chat.",
  "Wear your shirt backwards for the next hour.",
  "Make a dramatic slow-motion entrance into a room.",
  "Try to lick your elbow for 30 seconds straight.",
  "Do 15 squats while yelling 'I'm Batman'.",
  "Text someone randomly and say 'I know what you did'.",
  "Talk without using the letter 'A' for 2 minutes.",
  "Send a voice note of you meowing like a cat.",
  "Take a selfie with your weirdest face and post it.",
  "Speak in rhymes for the next 5 minutes.",
  "Record yourself reading a paragraph in a super dramatic voice.",
  "Say something flirty to a bot in the server.",
  "Share your most recent Google search.",
  "Send 'I'm sorry' to the last person you texted.",
  "Set your profile name to a food item for 1 hour.",
  "Send a GIF that describes your love life.",
  "Make up a breakup story and send it to a friend.",
  "Do 20 jumping jacks while singing a song.",
  "Act like a grandma/grandpa for 2 minutes.",
  "Pretend your hand is a phone and have a full conversation.",
  "Create a pickup line using the word 'banana'.",
  "Spell your name with your nose on your keyboard.",
  "Do a TikTok dance (or try your best).",
  "Send 'Can I borrow ₹5000?' to your crush.",
  "Say the word 'pickle' after everything you say for 3 minutes.",
  "Use only emojis to reply to messages for 5 minutes.",
  "Pretend to cry over spilled milk.",
  "Take a bite of a raw onion.",
  "Act like you just saw a ghost and narrate what happened.",
  "Balance a spoon on your nose for 30 seconds.",
  "Recreate a popular meme using your face.",
  "Do your best evil villain monologue.",
  "Make a weird confession (even if it’s fake).",
  "Read your last DM out loud in a dramatic tone.",
  "Sing a Bollywood song out loud.",
  "Try to do a headstand or handstand (attempt is enough).",
  "Let someone dare you in DMs and follow through.",
  "Text 'I can’t stop thinking about you 😳' to a friend.",
  "Act like a baby throwing a tantrum for 30 seconds.",
  "Pretend your shoe is a phone and answer a call.",
  "Create a poem about someone in the server.",
  "Record a 15-second rap about Discord.",
  "Talk like a robot for the next 2 minutes.",
  "Draw a mustache on your face and wear it for a selfie.",
  "Recreate a Bollywood scene with full drama.",
  "Show your last photo and explain the story.",
  "Eat a spoonful of ketchup or mayonnaise.",
  "Speak only using song lyrics for 3 minutes.",
  "Whisper your next 5 messages.",
  "Do your best impression of your favorite teacher.",
  "Send a risky text to your best friend.",
  "Post 'I believe in aliens' on your status.",
  "Take a fake crying selfie and share it.",
  "Talk like a villain and plot world domination.",
  "Send 'We need to talk' to someone random.",
  "Tell a joke so bad that it’s funny.",
  "Write a dramatic breakup message to a fictional person.",
  "Post a random fact about penguins in chat.",
  "Act like you're scared of your own shadow.",
  "Do a video saying 'I'm a potato' with a serious face.",
  "Say 'I’m secretly a lizard person' in general chat.",
  "Make a dramatic confession (real or fake).",
  "Eat something without using your hands.",
  "Speak only in third person for the next 5 minutes.",
  "Write a poem using only Discord usernames.",
  "Record yourself trying to rap a nursery rhyme.",
  "Start a conspiracy theory in voice chat.",
  "Send 'I miss you 😭' to a random server member.",
  "Describe your crush using emojis only.",
  "Try to draw your face blindfolded.",
  "Create a pickup line using a Discord emoji.",
  "Tell your pet (or a stuffed toy) your secrets.",
  "Make a new rule for the server (funny one).",
  "Change your profile pic to a random meme.",
  "Invent a new word and define it.",
  "Spell your name backward while doing jumping jacks.",
  "Say 'I love pineapple on pizza' 10 times fast.",
  "Write a haiku about someone in voice chat.",
  "Send a message in Morse code (use translator).",
  "Do a fake proposal in general chat.",
  "Wear a towel like a superhero cape.",
  "Try to sing a song backward.",
  "Do a video pretending you're an alien visiting Earth.",
  "Say a tongue twister 3 times fast.",
  "Pretend your keyboard is lava and react accordingly.",
  "Make a weird filter video and share it.",
  "Say something flirty to the last person who DMed you.",
  "Call someone and say “Guess what?” but don’t answer them.",
  "Send a selfie with toothpaste on your face.",
  "Make a slow-motion dramatic reaction video.",
  "Pretend you're livestreaming and narrate your room.",
  "Draw a potato and name it after a friend.",
  "Make a fake job application for ‘meme lord’.",
  "Do 5 animal impressions and let others guess.",
  "Explain how to eat cereal like it’s a life hack.",
  "Talk like you're in a cooking show for 2 minutes.",
  "Make a fake news announcement.",
  "Create a weird new Discord emoji idea and pitch it.",
  "Take a picture of your feet (with socks) and share it.",
  "Send ‘I lost the bet’ to someone with no explanation.",
  "Pretend to be a mirror for 1 minute.",
  "Sing your favorite song out loud.",
  "Dance with no music for 30 seconds.",
  "Change your nickname to something silly for 10 minutes.",
  "Send a meme without context.",
  "Imitate your favorite cartoon character.",
  "Wear socks on your hands for the next 5 minutes.",
  "Let someone send a message from your phone.",
  "Call a friend and say you love pineapple on pizza.",
  "Draw a mustache on your face with a pen.",
  "Balance a book on your head and walk.",
  "Do your best evil laugh.",
  "Send the last photo in your gallery.",
  "Record yourself singing badly and post it.",
  "Pretend you’re a robot for 2 minutes.",
  "Speak only in emojis for 3 minutes.",
  "Spin around 10 times and try to walk straight.",
  "Do 20 jumping jacks.",
  "Show your browser history.",
  "Say 3 embarrassing facts about yourself.",
  "Try to touch your toes for 30 seconds.",
  "Take a weird selfie and make it your profile picture.",
  "Pretend to cry for 1 minute.",
  "Share a cringy childhood story.",
  "Let someone else write your next message.",
  "Act like a cat for 1 minute.",
  "Attempt to lick your elbow.",
  "Text your mom something weird.",
  "Make a weird face and hold it for 10 seconds.",
  "Act like you're in love with your chair.",
  "Talk without using the letter ‘e’ for 1 minute.",
  "Take a sip of water while upside down.",
  "Sing the chorus of a song using only animal sounds.",
  "Say something romantic to a random person.",
  "Speak like a baby for 2 minutes.",
  "Show your last five emojis.",
  "Write your name with your non-dominant hand.",
  "Eat a lemon slice.",
  "Make a weird animal noise every time someone talks for 5 minutes.",
  "Pretend you're a news reporter reporting a fake story.",
  "Do your best runway walk.",
  "Try to sell something nearby as if you're a salesperson.",
  "Share an old embarrassing video or photo."
];

module.exports = {
  data: new SlashCommandBuilder()
    .setName('td') // ✅ new name
    .setDescription('Play Truth or Dare!')
    .addStringOption(option =>
      option.setName('choice')
        .setDescription('Choose truth or dare')
        .setRequired(true)
        .addChoices(
          { name: 'Truth', value: 'truth' },
          { name: 'Dare', value: 'dare' },
        )),

  async execute(interaction) {
    const choice = interaction.options.getString('choice');
    const list = choice === 'truth' ? truths : dares;
    const prompt = list[Math.floor(Math.random() * list.length)];

    await interaction.reply(`${interaction.user}, here’s your ${choice}: **${prompt}**`);
  }
};